doctrine:
    dbal:
        default_connection: "elections"
        connections:
            elections:
                dbname: '%env(DATABASE_NAME)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                port: '%env(DATABASE_PORT)%'
                host: '%env(DATABASE_HOST)%'
                server_version: '10.5'
                default_table_options:
                    collate: utf8mb4_general_ci
            courts:
                dbname: 'courts'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                port: '%env(DATABASE_PORT)%'
                host: '%env(DATABASE_HOST)%'
                server_version: '10.5'
                default_table_options:
                    collate: utf8mb4_general_ci
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Elections/Entity'
                        prefix: 'App\Elections\Entity'
                        alias: App
                dql:
                    string_functions:
                        MATCH_AGAINST: App\Doctrine\MatchAgainst
                        JSON_CONTAINS: Scienta\Doct
            courts:
                connection: "courts"
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Courts/Entity'
                        prefix: 'App\Courts\Entity'
                        alias: App
                dql:
                    string_functions:
                        MATCH_AGAINST: App\Doctrine\MatchAgainst
                        JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
                        JSON_LENGTH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonLength
