authentication_token:
  path: /auth
  methods: ['POST']

commission_print:
  path: /commissions/{id}/print
  methods: ['GET']
  defaults:
    _controller: App\Elections\Commission\GeneratePoster

commission_print_text:
  path: /commissions/{id}/print/text
  methods: ['GET']
  defaults:
    _controller: App\Elections\Commission\GeneratePosterWithoutPhoto

commission_upload:
  path: /commission/{id}/upload
  methods: ['POST']
  defaults:
    _controller: App\UploadAttachment

requests:
  path: /requests
  methods: ['GET']
  defaults:
    _controller: App\HelpRequest\GetListAction
request:
  path: /request
  methods: ['POST']
  defaults:
    _controller: App\HelpRequest\CreateRequest

commission_verify:
  path: /verification
  methods: ['POST']
  defaults:
    _controller: App\HonestPeople\VerifyObserver

add_decision:
  path: /api/decision
  methods: ['POST']
  defaults:
    _controller: App\Courts\AddDecision

edit_decision:
  path: /api/decision/{id}
  methods: ['PATCH']
  defaults:
    _controller: App\Courts\EditDecision

statistic:
  path: /statistic
  defaults:
    _controller: App\Courts\GetStatisticsAction

unsubscribe:
  path: /unsubscribe/{uid}/{hash}
  methods: ['GET']
  defaults:
    _controller: App\Unsubscribe

courts_hash:
  path: /courts/hash
  methods: [ 'GET' ]
  defaults:
    _controller: App\Courts\GetCurrentContentHashAction
