# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $projectDir: "%kernel.project_dir%"
      $sheetId: "env(SHEET_ID)"
      $bucketMembers: "%env(BUCKET_MEMBERS)%"
      $bucketReports: "%env(BUCKET_REPORTS)%"
      $unsubscribeSecret: "%env(UNSUBSCRIBE_SECRET)%"
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Doctrine/Migrations,Tests,Kernel.php,functions.php}'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Elections\MapViewFilter: ~

  App\SearchByAllFields: ~

  App\Elections\Commission\ContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    arguments: [ '@App\Elections\Commission\ContextBuilder.inner' ]
    autoconfigure: false

  App\InitializeDatabase: ~

  App\SwaggerDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    arguments: [ '@App\SwaggerDecorator.inner' ]
    autoconfigure: false

  App\Elections\Commission\GeneratePoster:
    tags: [ 'controller.service_arguments' ]

  App\Elections\Commission\PosterRenderer: ~

  App\Elections\Commission\GeneratePosterWithoutPhoto:
    tags: [ 'controller.service_arguments' ]

  App\Elections\HonestPeople\VerifyObserver:
    tags: [ 'controller.service_arguments' ]

  App\HelpRequest\CreateRequest:
    tags: [ 'controller.service_arguments' ]

  App\UploadAttachment:
    tags: [ 'controller.service_arguments' ]

  App\HelpRequest\GetListAction:
    tags: [ 'controller.service_arguments' ]

  App\Unsubscribe:
    tags: [ 'controller.service_arguments' ]

  App\Courts\LoadJudges:
    arguments: [ '@doctrine.dbal.courts_connection' ]

  App\Courts\LoadHistory:
    arguments: [ '@doctrine.dbal.courts_connection' ]

  App\Courts\GetStatisticsAction:
    arguments: [ '@doctrine.dbal.courts_connection' ]
    tags: [ 'controller.service_arguments' ]

  App\Courts\AddDecision:
    arguments: [ '@doctrine.dbal.courts_connection' ]
    tags: [ 'controller.service_arguments' ]

  App\Courts\EditDecision:
    arguments: [ '@doctrine.dbal.courts_connection' ]
    tags: [ 'controller.service_arguments' ]

  App\Courts\LoadImagesLocal:
    arguments: [ '@doctrine.dbal.courts_connection' ]

  App\Courts\UpdateFromSpring96:
    arguments: [ '@doctrine.dbal.courts_connection' ]

  App\Courts\LoadCourts:
    arguments: [ '@doctrine.dbal.courts_connection' ]

  App\Courts\UpdateJudges:
    arguments: [ '@doctrine.dbal.courts_connection' ]

  App\Courts\GenerateContentForHugo:
    arguments: [ '@doctrine.orm.courts_entity_manager' ]

  'App\Normalizer':
    decorates: 'api_platform.jsonld.normalizer.item'
    arguments: [ '@App\Normalizer.inner' ]

  App\Courts\GetTop10JudgesCommand:
    arguments: [ '@doctrine.dbal.courts_connection' ]

  App\Courts\FindMissingJudgesCommand:
    arguments: [ '@doctrine.dbal.courts_connection' ]
