- hosts: backend
  gather_facts: no

  tasks:
    - name: install php
      apt:
        pkg:
          - php7.4-fpm
          - php7.4-mysql
          - php7.4-mbstring
          - php7.4-xml
          - php7.4-curl
          - php7.4-gd
          - php7.4-iconv
          - php7.4-ctype
    - name: www-conf
      copy:
        src: php/www_conf_prod.conf
        dest: /etc/php/7.4/fpm/pool.d/www.conf
        force: yes
    - name: php-ini
      copy:
        src: php/php_prod.ini
        dest: /etc/php/7.4/fpm/php.ini
        force: yes
    - name: reload php-fpm
      systemd:
        name: php7.4-fpm
        state: reloaded
