- hosts: all
  gather_facts: no

  tasks:
    - name: add deploy user
      user:
        name: deploy
        shell: /bin/bash

    - name: add deploy group
      group:
        name: deploy

    - name: Set authorized key taken from file
      authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', 'credentials/pub.key') }}"

    - name: Create a directory if it does not exist
      file:
        path: /api
        state: directory
        recurse: yes
        owner: deploy
        group: deploy

    - name: install php
      apt:
        pkg:
          - php7.4-fpm
          - php7.4-mysql
          - php7.4-mbstring
          - php7.4-xml
          - php7.4-curl
          - php7.4-gd
    - name: www-conf
      copy:
        src: php/www_conf_prod.conf
        dest: /etc/php/7.4/fpm/pool.d/www.conf
        force: yes
    - name: php-ini
      copy:
        src: php/php_prod.ini
        dest: /etc/php/7.4/fpm/php.ini
        force: yes
    - name: reload php-fpm
      systemd:
        name: php7.4-fpm
        state: reloaded
