- debug:
    msg: System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}
#
#- name: status
#  shell: '{{ ansistrano_release_path.stdout }}/bin/console update:members'
#  register: output
