
- name: update members if needed
  shell: '{{ ansistrano_release_path.stdout }}/bin/console update:members'
  when: inventory_hostname in groups['data']
  register: update
- debug: var=update.stdout_lines

- name: update judges if needed
  shell: '{{ ansistrano_release_path.stdout }}/bin/console update:judges'
  when: inventory_hostname in groups['data'] and HAS_CHANGE == 'true'
  register: update
- debug: var=update.stdout_lines

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: '{{ ansistrano_release_path.stdout }}'
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
