version: '3.4'

services:
  php:
    build:
      context: './../'
      dockerfile: 'infrastructure/php/Dockerfile'
    volumes:
      - "../.:/app"
    # output of `echo $(id -u ${USER}):$(id -g ${USER})`
    user: ${HOST_UID}
    command: ["php-fpm"]
    networks:
      - app-network

  nginx:
    image: nginx:1.19-alpine
    depends_on:
      - php
    ports:
      - "9010:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./../public:/app/public:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
