version: '3.4'
services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=zubr_prod
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGPASSWORD=${DATABASE_PASSWORD}
    networks:
      - app-network


