version: '3.4'

services:
  php:
    environment:
      PHP_IDE_CONFIG: serverName=symfony-docker
    command:
      - "php-fpm"
      - "--allow-to-run-as-root"
      - "-d"
      - "xdebug.mode=debug"
      - "-d"
      - "xdebug.discover_client_host=1"
