version: '3.4'
services:
  database:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGPASSWORD=${DATABASE_PASSWORD}
    networks:
      - app-network


