pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Back-end') {
        agent {
            dockerfile {
                filename 'infrastructure/php/gitlab/Dockerfile'
            }
        }
        steps {
            sh 'composer install -a --no-dev --no-interaction'
        }
    }
  }
}

